env:
  browser: true
  es2024: true
root: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier'
  - 'plugin:prettier/recommended'
plugins:
  - '@typescript-eslint'
  - 'eslint-plugin-prettier/recommended'
  - 'testing-library'
parserOptions:
  parser: '@typescript-eslint/parser'
  ecmaVersion: 'latest'
  sourceType: 'module'
ignorePatterns:
  - '**/node_modules/**'
  - dist/*
  - dbdata/*
  - .github/*
  - src-tauri/*
  - '*.yaml'
rules:
  no-prototype-builtins: 'off'
  '@typescript-eslint/consistent-type-imports': 'error'
overrides:
  - files:
      - '**/*.spec.ts'
    extends:
      - 'plugin:testing-library/dom'
    rules:
      testing-library/prefer-screen-queries: 'off'
