env:
  browser: true,
  es2024: true,
extends: ["eslint:recommended", "plugin:@typescript-eslint/recommended"]
plugins: ["@typescript-eslint"]
parserOptions:
  parser: "@typescript-eslint/parser"
  ecmaVersion: "latest"
  sourceType: "module"
root: true
ignorePatterns: ["node_modules/", "dist/", "dbdata/", ".github/", "src-tauri/"]
rules: { no-prototype-builtins: "off" }
